/* SQL Manager for InterBase and Firebird 5.2.6.45382 */
/* -------------------------------------------------- */
/* Host     : localhost                               */
/* Database : C:\DATA\COMPARSA\COMPARSA.FDB           */


CREATE DATABASE 'localhost/3050:C:\DATA\COMPARSA\COMPARSA.FDB'   USER 'SYSDBA'
   PAGE_SIZE 4096
   DEFAULT CHARACTER SET WIN1252;

/* Definition for the `D_INTEGER` domain :  */

CREATE DOMAIN D_INTEGER AS
  INTEGER;

/* Definition for the `D_MEMOBLOB512` domain :  */

CREATE DOMAIN D_MEMOBLOB512 AS
  BLOB SUB_TYPE 1 SEGMENT SIZE 512;

/* Definition for the `D_VARCHAR100` domain :  */

CREATE DOMAIN D_VARCHAR100 AS
  VARCHAR(100);

/* Definition for the `D_VARCHAR50` domain :  */

CREATE DOMAIN D_VARCHAR50 AS
  VARCHAR(50);

/* Structure for the `LOCALIDAD` table :  */

CREATE TABLE LOCALIDAD (
  LOCALIDADID D_INTEGER NOT NULL,
  NOMBRE D_VARCHAR100,
  ESTADO D_VARCHAR50,
  MUNICIPIO D_VARCHAR50,
  NOTAS D_MEMOBLOB512);


ALTER TABLE LOCALIDAD ADD CONSTRAINT PK_LOCALIDAD PRIMARY KEY (LOCALIDADID);

/* Definition for the `D_SMALLINT` domain :  */

CREATE DOMAIN D_SMALLINT AS
  SMALLINT;

/* Definition for the `D_VARCHAR10` domain :  */

CREATE DOMAIN D_VARCHAR10 AS
  VARCHAR(10);

/* Definition for the `D_VARCHAR200` domain :  */

CREATE DOMAIN D_VARCHAR200 AS
  VARCHAR(200);

/* Structure for the `AFECTADO` table :  */

CREATE TABLE AFECTADO (
  AFECTADOID D_INTEGER NOT NULL,
  CODIGO D_VARCHAR10,
  NOMBRE D_VARCHAR100,
  ESTATUS D_SMALLINT,
  CALLE D_VARCHAR50,
  NUMEXT D_VARCHAR10,
  NUMINT D_VARCHAR10,
  COLONIA D_VARCHAR50,
  MUNICIPIO D_VARCHAR50,
  ESTADO D_VARCHAR50,
  TELEFONO D_VARCHAR50,
  EMAIL D_VARCHAR50,
  TWITTER D_VARCHAR200,
  FACEBOOK D_VARCHAR200,
  DICTAMEN D_MEMOBLOB512,
  NOTAS D_MEMOBLOB512,
  LOCALIDADID D_INTEGER);


ALTER TABLE AFECTADO ADD CONSTRAINT PK_AFECTADO PRIMARY KEY (AFECTADOID);

ALTER TABLE AFECTADO ADD CONSTRAINT FK_AFECTADO_LOCALIDAD FOREIGN KEY (LOCALIDADID) REFERENCES LOCALIDAD(LOCALIDADID);

/* Definition for the `AFECTADO_ID_GEN` generator :  */

CREATE GENERATOR AFECTADO_ID_GEN;

/* Definition for the `BI_AFECTADO_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_AFECTADO_ID FOR AFECTADO
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.AFECTADOID IS NULL) THEN
      NEW.AFECTADOID = GEN_ID(AFECTADO_ID_GEN, 1);
END^

SET TERM ; ^

/* Structure for the `TIPOARTICULO` table :  */

CREATE TABLE TIPOARTICULO (
  TIPOARTICULOID D_INTEGER NOT NULL,
  NOMBRE D_VARCHAR100);


ALTER TABLE TIPOARTICULO ADD CONSTRAINT PK_TIPOARTICULO PRIMARY KEY (TIPOARTICULOID);

/* Definition for the `D_VARCHAR20` domain :  */

CREATE DOMAIN D_VARCHAR20 AS
  VARCHAR(20);

/* Structure for the `ARTICULO` table :  */

CREATE TABLE ARTICULO (
  ARTICULOID D_INTEGER NOT NULL,
  CODIGO D_VARCHAR20,
  NOMBRE D_VARCHAR100,
  TIPOARTICULOID D_INTEGER,
  TOTALENTRADAS D_INTEGER,
  TOTALSALIDAS D_INTEGER);


ALTER TABLE ARTICULO ADD CONSTRAINT PK_ARTICULO PRIMARY KEY (ARTICULOID);

ALTER TABLE ARTICULO ADD CONSTRAINT FK_ARTICULO_TIPOARTICULO FOREIGN KEY (TIPOARTICULOID) REFERENCES TIPOARTICULO(TIPOARTICULOID);

/* Definition for the `ARTICULO_ID_GEN` generator :  */

CREATE GENERATOR ARTICULO_ID_GEN;

/* Definition for the `BI_ARTICULO_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_ARTICULO_ID FOR ARTICULO
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ARTICULOID IS NULL) THEN
      NEW.ARTICULOID = GEN_ID(ARTICULO_ID_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `D_BOOL` domain :  */

CREATE DOMAIN D_BOOL AS
  SMALLINT
  DEFAULT 0
  CHECK (VALUE IN (0,1));

/* Structure for the `COLABORADOR` table :  */

CREATE TABLE COLABORADOR (
  COLABORADORID D_INTEGER NOT NULL,
  CODIGO D_VARCHAR10,
  NOMBRE D_VARCHAR100,
  CALLE D_VARCHAR50,
  NUMEXT D_VARCHAR10,
  NUMINT D_VARCHAR10,
  COLONIA D_VARCHAR50,
  MUNICIPIO D_VARCHAR50,
  ESTADO D_VARCHAR50,
  ESBRIGADISTA D_BOOL,
  ESDONANTE D_BOOL,
  INSTITUCION D_VARCHAR100,
  NOTAS D_MEMOBLOB512,
  TWITTER D_VARCHAR200,
  FACEBOOK D_VARCHAR200,
  TELEFONO D_VARCHAR50,
  EMAIL D_VARCHAR50,
  POBLACION D_VARCHAR50,
  REFERIDOPOR D_VARCHAR100);


ALTER TABLE COLABORADOR ADD CONSTRAINT PK_COLABORADOR PRIMARY KEY (COLABORADORID);

/* Definition for the `COLABORADOR_ID_GEN` generator :  */

CREATE GENERATOR COLABORADOR_ID_GEN;

/* Definition for the `BI_COLABORADOR_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_COLABORADOR_ID FOR COLABORADOR
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF ((NEW.COLABORADORID IS NULL) OR (NEW.COLABORADORID = 0)) THEN
      NEW.COLABORADORID = GEN_ID(COLABORADOR_ID_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `D_DATE` domain :  */

CREATE DOMAIN D_DATE AS
  DATE;

/* Definition for the `D_TIME` domain :  */

CREATE DOMAIN D_TIME AS
  TIME;

/* Structure for the `ENTRADA` table :  */

CREATE TABLE ENTRADA (
  ENTRADAID D_INTEGER NOT NULL,
  NUMERO D_VARCHAR10,
  FECHA D_DATE,
  HORA D_TIME,
  DONANTEID D_INTEGER,
  RESPONSABLEID D_INTEGER,
  NOTAS D_MEMOBLOB512);


ALTER TABLE ENTRADA ADD CONSTRAINT PK_ENTRADA PRIMARY KEY (ENTRADAID);

/* Definition for the `ENTRADA_ID_GEN` generator :  */

CREATE GENERATOR ENTRADA_ID_GEN;

/* Definition for the `BI_ENTRADA_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_ENTRADA_ID FOR ENTRADA
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ENTRADAID IS NULL) THEN
      NEW.ENTRADAID = GEN_ID(ENTRADA_ID_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `LOCALIDAD_ID_GEN` generator :  */

CREATE GENERATOR LOCALIDAD_ID_GEN;

/* Definition for the `BI_LOCALIDAD_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_LOCALIDAD_ID FOR LOCALIDAD
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.LOCALIDADID IS NULL) THEN
      NEW.LOCALIDADID = GEN_ID(LOCALIDAD_ID_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `TIPOARTICULO_ID_GEN` generator :  */

CREATE GENERATOR TIPOARTICULO_ID_GEN;

/* Definition for the `BI_TIPOARTICULO_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_TIPOARTICULO_ID FOR TIPOARTICULO
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.TIPOARTICULOID IS NULL) THEN
      NEW.TIPOARTICULOID = GEN_ID(TIPOARTICULO_ID_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `D_BIGINT` domain :  */

CREATE DOMAIN D_BIGINT AS
  BIGINT;

/* Definition for the `D_BLOB1024` domain :  */

CREATE DOMAIN D_BLOB1024 AS
  BLOB SEGMENT SIZE 1024;

/* Definition for the `D_BLOB1024_1` domain :  */

CREATE DOMAIN D_BLOB1024_1 AS
  BLOB SUB_TYPE 1 SEGMENT SIZE 1024;

/* Definition for the `D_BLOB512` domain :  */

CREATE DOMAIN D_BLOB512 AS
  BLOB SEGMENT SIZE 512;

/* Definition for the `D_CALLEDOMICILIO` domain :  */

CREATE DOMAIN D_CALLEDOMICILIO AS
  VARCHAR(50);

/* Definition for the `D_COLONIA` domain :  */

CREATE DOMAIN D_COLONIA AS
  VARCHAR(50);

/* Definition for the `D_COLONIADOMICILIO` domain :  */

CREATE DOMAIN D_COLONIADOMICILIO AS
  VARCHAR(50);

/* Definition for the `D_CONTACTO` domain :  */

CREATE DOMAIN D_CONTACTO AS
  VARCHAR(60);

/* Definition for the `D_DOMICILIO` domain :  */

CREATE DOMAIN D_DOMICILIO AS
  VARCHAR(100);

/* Definition for the `D_EMAIL` domain :  */

CREATE DOMAIN D_EMAIL AS
  VARCHAR(60);

/* Definition for the `D_ESTADO` domain :  */

CREATE DOMAIN D_ESTADO AS
  VARCHAR(5);

/* Definition for the `D_ESTADODOMICILIO` domain :  */

CREATE DOMAIN D_ESTADODOMICILIO AS
  VARCHAR(50);

/* Definition for the `D_FLOAT` domain :  */

CREATE DOMAIN D_FLOAT AS
  FLOAT;

/* Definition for the `D_MEMO` domain :  */

CREATE DOMAIN D_MEMO AS
  VARCHAR(500);

/* Definition for the `D_NUMERIC_15_2` domain :  */

CREATE DOMAIN D_NUMERIC_15_2 AS
  NUMERIC(15, 2)
  DEFAULT 0;

/* Definition for the `D_NUMERIC_15_3` domain :  */

CREATE DOMAIN D_NUMERIC_15_3 AS
  NUMERIC(15, 3);

/* Definition for the `D_NUMERIC_15_4` domain :  */

CREATE DOMAIN D_NUMERIC_15_4 AS
  NUMERIC(15, 4)
  DEFAULT 0;

/* Definition for the `D_NUMERIC_15_5` domain :  */

CREATE DOMAIN D_NUMERIC_15_5 AS
  NUMERIC(15, 5);

/* Definition for the `D_NUMERIC_15_6` domain :  */

CREATE DOMAIN D_NUMERIC_15_6 AS
  NUMERIC(15, 6);

/* Definition for the `D_NUMERIC_18_8` domain :  */

CREATE DOMAIN D_NUMERIC_18_8 AS
  NUMERIC(18, 8)
  DEFAULT 0;

/* Definition for the `D_NUMERIC_5_1` domain :  */

CREATE DOMAIN D_NUMERIC_5_1 AS
  NUMERIC(5, 1);

/* Definition for the `D_NUMERODOMICILIO` domain :  */

CREATE DOMAIN D_NUMERODOMICILIO AS
  VARCHAR(10);

/* Definition for the `D_PAIS` domain :  */

CREATE DOMAIN D_PAIS AS
  VARCHAR(40);

/* Definition for the `D_PHONE` domain :  */

CREATE DOMAIN D_PHONE AS
  VARCHAR(30);

/* Definition for the `D_PHONEEXT` domain :  */

CREATE DOMAIN D_PHONEEXT AS
  VARCHAR(5);

/* Definition for the `D_PICTURE` domain :  */

CREATE DOMAIN D_PICTURE AS
  BLOB SUB_TYPE 1 SEGMENT SIZE 4000;

/* Definition for the `D_POBLACION` domain :  */

CREATE DOMAIN D_POBLACION AS
  VARCHAR(50);

/* Definition for the `D_RFC` domain :  */

CREATE DOMAIN D_RFC AS
  VARCHAR(20);

/* Definition for the `D_SHORTTEXT` domain :  */

CREATE DOMAIN D_SHORTTEXT AS
  VARCHAR(30);

/* Definition for the `D_TEXT` domain :  */

CREATE DOMAIN D_TEXT AS
  VARCHAR(100);

/* Definition for the `D_TIMESTAMP` domain :  */

CREATE DOMAIN D_TIMESTAMP AS
  TIMESTAMP;

/* Definition for the `D_VARCHAR_3` domain :  */

CREATE DOMAIN D_VARCHAR_3 AS
  VARCHAR(3);

/* Definition for the `D_VARCHAR_5` domain :  */

CREATE DOMAIN D_VARCHAR_5 AS
  VARCHAR(5);

/* Definition for the `D_VARCHAR1` domain :  */

CREATE DOMAIN D_VARCHAR1 AS
  VARCHAR(1);

/* Definition for the `D_VARCHAR3` domain :  */

CREATE DOMAIN D_VARCHAR3 AS
  VARCHAR(3);

/* Definition for the `D_VARCHAR30` domain :  */

CREATE DOMAIN D_VARCHAR30 AS
  VARCHAR(30);

/* Definition for the `D_VARCHAR300` domain :  */

CREATE DOMAIN D_VARCHAR300 AS
  VARCHAR(300);

/* Definition for the `D_VARCHAR5` domain :  */

CREATE DOMAIN D_VARCHAR5 AS
  VARCHAR(5);

/* Definition for the `D_ZIPCODE` domain :  */

CREATE DOMAIN D_ZIPCODE AS
  VARCHAR(10);

/* Privileges for the `AFECTADO` :  */


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON AFECTADO TO SYSDBA WITH GRANT OPTION;


/* Privileges for the `ARTICULO` :  */


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON ARTICULO TO SYSDBA WITH GRANT OPTION;


/* Privileges for the `COLABORADOR` :  */


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON COLABORADOR TO SYSDBA WITH GRANT OPTION;


/* Privileges for the `ENTRADA` :  */


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON ENTRADA TO SYSDBA WITH GRANT OPTION;


/* Privileges for the `LOCALIDAD` :  */


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON LOCALIDAD TO SYSDBA WITH GRANT OPTION;


/* Privileges for the `TIPOARTICULO` :  */


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TIPOARTICULO TO SYSDBA WITH GRANT OPTION;

